### ISSUE TITLE
Not Picking up on Language Comment Settings

### ISSUE THREAD

**Issue by TDGithubIntegration** [taicho/todo-plus#3]
There is no directive on how to format the json, so I'm going by the vs code intellisense suggestions. This code does not work, even after a restart:
```
    "todoPlus.languages": [
        {
            "lineComment": ";",
            "extensions": [".ahk"],
            "blockComment": ["/**/"]
        }
    ]
```

**Comment by taicho** [comment]
@TDGithubIntegration Good point on the lack of directive - I've added some basic documentation on how to add custom language support. That being said, I believe the issue was in the format of your block comment, I was able to get all Todo Plus functionality working for your proposed language definition with the following:
```json
    "todoPlus.languages": [
        {
            "lineComment": ";",
            "extensions": [".ahk"],
            "blockComment": ["/*","*/"] <--- Notice the seperation in the block comment e.g. start and end.
        }
    ]
```

I was able to get this working with no code changes - let know if this does/doesn't work for you?

**Comment by TDGithubIntegration** [comment]
Hello Azad,

Thank you for looking into it! That change works perfectly.

Best,

Julian
